= Solution design

== Inleiding

Dit ontwerp beschrijft de beoogde gebruiksscenario’s voor het
dataproduct _GV Meetdata_, alsmede de achterliggende architectuur en
gemaakte keuzes.

== Reikwijdte

Er is steeds meer behoefte aan inzicht in data over energieverbruik en
energieopwekking van grootverbruikers (GV) om optimaal gebruik te maken
van de beschikbare energiecapaciteit. Deze data is bijvoorbeeld relevant
voor bedrijven die willen samenwerken op een industrieterrein of voor
organisaties die individuele bedrijven willen helpen met duurzame
energie oplossingen en energiebesparingen. De GV-klant is eigenaar van
deze data en moet toestemming geven aan andere partijen om de data te
gebruiken. Een erkend meetverantwoordelijke (MV) verzorgt de metingen
van deze data.

Dit ontwerp beschrijft het proces om tot ontsluiting van het
bijbehorende dataproduct te komen en de betekenis & structuur van het
dataproduct.

== Achtergrond

Onderstaand wordt kort de achtergrond toegelicht m.b.t. dataproducten.

=== Dataproduct

Voor alle data-uitwisseling binnen de scope van de visie is expliciet
gekozen voor het denken over data in de vorm van dataproducten. Een
dataproduct combineert de semantische-, technische- en gebruiksaspecten
van data-uitwisseling. Om dit invulling te geven bestaat een dataproduct
uit de volgende componenten:

* _dataset_: de daadwerkelijke gegevens die worden uitgewisseld. Zie een
dataset als een tabel met gegevens, waarbij de kolommen beschrijven wat
er op elke rij van de data aan gegevens wordt geleverd. Een dataset voor
aansluitingen zal minstens een kolom "`Aansluitingsnummer`" bevatten,
waarbij elke rij in de dataset een aansluiting beschrijft;
* _dataservice_: de technische manier van verspreiden van de dataset.
Dit gaat over hoe de data ontsloten wordt (als bestand, API, database of
_file server_);
* _voorwaarden_: er kunnen voorwaarden liggen op beschikbaarheid,
kwaliteit, classificatie en doelbinding bij gebruik van het dataproduct.

Het dataproduct combineert de _dataset_ en _dataservice_, verrijkt met
_voorwaarden_ voor gebruik.

=== Volume, variety, veracity, velocity

Data kent vier kenmerken:

* _volume_: data kent een volume, een hoeveelheid;
* _variety_ (variëteit): data is te verdelen in gestructureerde en
ongestructureerde data. Ongestructureerde data kent geen metamodel;
* _veracity_ (betrouwbaarheid): de mate waarin de data vertrouwd kan
worden voor de toepassing;
* _velocity_ (snelheid): de frequentie waarmee data verandert.

== Functionele eisen

Het dataproduct is onderheving aan functionele eisen: wat het
dataproduct moet _doen_.

[width="100%",cols="1,4,3",options="header"]
|===
|Als |Wil ik |Want
|GV-klant |Een uniform overzicht van gemeten energieverbruik (E&G,
invoeding en afname), in kwartier- en/of uurwaarden per meetinstallatie
|Ik wens inzicht in mijn verbruik

|GV-klant |Via self-service (MijnOmgeving, centraal meetdataregister)
mijn meetgegevens ophalen |Ik wens zo snel mogelijk mijn
verbruiksgegevens ontvangen

|GV-klant |Een service desk om online vragen te kunnen stellen |Ik wens
ondersteuning bij gebruik van mijn verbruiksgegevens

|Derde |Een uniform overzicht van gemeten energieverbruik (E & G,
invoeding en afname), in kwartierwaarden per meetinstallatie |Ik wens
inzicht in het verbruik van de aangeslotene(n)

|Derde |Een service desk om online vragen te kunnen stellen |Ik wens
ondersteuning bij gebruik van het dataproduct

|Netbeheerder |Gemeten energieverbruik via de MijnOmgeving ontsluiten
|Ik wil mijn klant faciliteren in het inzicht in verbruiksgegevens

|Netbeheerder |Een uniform overzicht van gemeten energieverbruik kunnen
ontsluiten via de MijnOmgeving |Ik wens mijn GV-klant te ondersteunen
bij inzicht in de verbruiksgegevens

|Netbeheerder |Een service desk om tweede- en derdelijns vragen te
kunnen stellen over levering via de MijnOmgeving |Ik ondervind mogelijk
problemen bij het leveren van verbruiksgegevens

|Netbeheerder |GV-klanten en derden doorverwijzen naar een _Centraal
Dataportaal_ |Ik wens een uniforme ontsluiting van verbruiksgegevens
voor zowel GV-klant als derde

|Netbeheerder |Verbruiksgegevens onder de juiste grondslag kunnen
leveren voor GV-klant en derde |Ik wens in lijn te zijn met wet- en
regelgeving
|===

== Dataservice

In beide gebruiksscenario’s vraagt de GV-klant of een _derde_ (zoals een
adviesbureau of ontwikkelbedrijf) meetgegevens op bij de netbeheerder
van een GV-klant. Indien een derde meetgegevens opvraagt dient
toestemming verleend te worden door de aangeslotene. Hierbij vervult de
GV-klant de rol van _aangeslotene_.

____
Beide gebruiksscenario’s gaan uit van _geauthenticeerde rollen_. Voor
authenticatie dient aangesloten te worden op bestaande processen. Indien
er geen _enrolment- en authenticatieproces_ is _moet_ deze worden
ingericht.
____

De gebruiksscenario’s beschrijven niet het uitvalproces (_happy flow_),
deze stappen dienen apart beschreven en geïmplementeerd te worden.

=== Gebruiksscenario: centraal dataproduct

.Gebruiksscenario
[d2,theme=4]
----
vars: {
  d2-config: {
    pad: 0
  }
}
direction: right
shape: sequence_diagram
gvKlant: "GV-klant / Derde"
register: "Meetdataregister (EDSN)"
platform: "Toestemmingsplatform"
aangeslotene: "Aangeslotene"
gvKlant.vraagop -> register.vraagop: "1. Vraag meetgegevens op"
register.vraagop -> platform.vraagop: "2. Is toestemming gegeven?"
alt: "Alt" {
  platform.vraagop -> aangeslotene.vraagop: "3. Toestemming vragen"
  aangeslotene.vraagop -> platform.vraagop: "4. Toestemming geven"
}
platform.vraagop -> register.vraagop: "5. Toestemming gegeven"
register.vraagop -> gvKlant.vraagop: "6. Lever meetgegevens"
----

. een _GV-klant_ of een _derde_ (e.g. een ontwikkelbedrijf) vraagt
meetgegevens op voor één of meerdere aansluitingen bij het _EDSN
meetdataregister_. GV-klanten vragen meetdata aan voor eigen
aansluiting(en), derden voor te specificeren aansluitingen;
. het meetdataregister toetst of er toestemming is verleend voor de
combinatie derde/aansluiting. Indien de GV-klant meetdata voor eigen
aansluiting(en) aanvraagt is toestemming niet vereist en wordt de
meetdata geleverd (stap 6);
. indien er geen toestemming is voor opvragen van de meetdata wordt de
_aangeslotene_ gevraagd deze te verlenen. De aangeslotene kan potentieel
weken wachten voordat toestemming verleend of afgewezen wordt;
. de verleende toestemming wordt vastgelegd in het Toestemmingplatform;
. het Toestemmingplatform notificeert het meetdataregister dat
toestemming verleend is door de aangeslotene;
. het meetdataregister levert de meetgegevens, onder het _uniforme
schema_.

Het beschreven scenario kent een aantal varianten voor implementatie:

* de netbeheerder leidt _GV-klanten_ vanuit de _Mijn-omgeving_ door naar
het meetdataregister;
* de netbeheerder leidt _derden_ door naar het meetdataregister;
* de netbeheerder ontsluit het meetdataregister vanuit de Mijn-omgeving.
Hiervoor vraagt de netbeheerder onder eigen autorisatie de meetgegevens
op voor de geauthenticeerde GV-klant;
* de netbeheerder ontsluit het meetdataregister vanuit de partner- of
derdenomgeving. Een derde vraagt voor specifieke aansluiting(en)
meetgegevens op, welke na toestemming van de aangeslotene worden
geleverd. Niet alle netbeheerders kennen een dergelijke partneromgeving.

=== Gebruikersscenario: decentraal dataproduct

.Gebruiksscenario
[d2,theme=4]
----
vars: {
  d2-config: {
    pad: 0
  }
}
direction: right
shape: sequence_diagram
gvKlant: "GV-klant / Derde"
netbeheerder: "Netbeheerder"
aangeslotene: "Aangeslotene"
gvKlant.vraagop -> netbeheerder.vraagop: "1. Vraag meetgegevens op"
netbeheerder.toestemming -> netbeheerder.toestemming: "2. Is toestemming gegeven?"
alt: "Alt" {
  netbeheerder.vraagop -> aangeslotene.vraagop: "3. Toestemming vragen"
  aangeslotene.vraagop -> netbeheerder.vraagop: "4. Toestemming geven"
}
netbeheerder.vraagop -> gvKlant.vraagop: "5. Lever meetgegevens"
----

. een _GV-klant_ of een _derde_ (e.g. een ontwikkelbedrijf) vraagt
meetgegevens op voor één of meerdere aansluitingen bij de netbeheerder.
GV-klanten vragen meetdata aan voor eigen aansluiting(en), derden voor
te specificeren aansluitingen;
. de netbeheerder toetst of er toestemming is verleend voor de
combinatie derde/aansluiting. Indien de GV-klant meetdata voor eigen
aansluiting(en) aanvraagt is toestemming niet vereist en wordt de
meetdata geleverd (stap 5);
. indien er geen toestemming is voor opvragen van de meetdata wordt de
_aangeslotene_ gevraagd deze te verlenen. De aangeslotene kan potentieel
weken wachten voordat toestemming verleend of afgewezen wordt;
. de verleende toestemming wordt vastgelegd in de administratie van de
netbeheerder;
. de netbeheerder levert de meetgegevens, onder het _uniforme schema_.

Het beschreven scenario kent een aantal varianten voor implementatie:

* de netbeheerder levert meetdata als voor de _GV-klant_ vanuit de
_Mijn-omgeving_;
* de netbeheerder levert meetdata als _maatwerkverzoek_ vanuit de eigen
_service desk_, of gedelegeerd naar _Partners in Energie_.

=== Architectuur

Vanuit architectuurperspectief zijn de volgende keuzes gemaakt:

.Architectuur
image::architecture-20241118.svg[Architectuur]

* de structuur (logisch model) van de dataset is gebaseerd op het
https://begrippen.netbeheernederland.nl/[conceptuele model
Begrippenmodel NBNL] en het https://cim-mg.ucaiug.io/latest/[Common
Information Model];
* het dataproduct _GV Meetdata_ is vindbaar via het EDSN Dataportaal.

== Dataset

=== Volume, variety, veracity, velocity

[width="100%",cols="14%,86%",options="header",]
|===
|Type |Beschrijving
|Volume |Laag, < 100MB (ongecomprimeerd).

|Variety |Gestructureerd.

|Veracity |Hoog, de dataset wordt samengesteld uit brongegevens die ook
voor facturatie worden ingezet.

|Velocity |Laag, datasets worden op verzoek samengesteld.
|===

== Voorwaarden

Dit dataproduct wordt als
https://github.com/Netbeheer-Nederland/am-doelarchitectuur-datadelen/blob/cebef14d35eaedd808cf9cb9ec7e931d0c5178c3/assets/20230217_NBNL_T5_Visie%20op%20datadelen_V1.01.pdf[gesloten
data] aangeboden, onder de
https://www.autoriteitpersoonsgegevens.nl/themas/basis-avg/avg-algemeen/grondslag-toestemming[Grondslag
toestemming]. De grondslag is vereist indien een derde de aanvraag doet,
voor een GV-klant is toestemming *niet* vereist indien het om meetdata
van de eigen aansluiting(en) gaat.

== Beslissingen en aannames

[width="100%",cols="16%,84%",options="header",]
|===
|Type |Beschrijving
|Aanname |Netbeheerders hebben de gevraagde meetgegevens (dataset)
beschikbaar voor levering als decentraal dataproduct

|Aanname |EDSN maakt geen aanpassingen in de bestaande interface(s) voor
het decentrale dataproduct

|Aanname |De aangeslotene verleent toestemming over toegang tot _al_
haar meetdata behorende bij een aansluiting. Dit voorkomt
toestemmingverzoeken voor meetgegevens in een tijdsperiode

|Aanname |Zowel GV-klant, als aangeslotene, als derde zijn te
identificeren, authenticeren en te benaderen voor communicatie

|Aanname |Toestemming wordt verleend op basis van de combinatie
derde/aansluiting

|Aanname |_Partners in Energie_ stopt met het invullen van
maatwerkverzoeken voor meetdata na implementatie van het centrale
dataproduct

|Aanname |De geldigheid van een verleende toestemming is minstens 90
dagen, om aantal toestemmingsverzoeken te beperken

|Aanname |Er wordt op sectorniveau een _Centraal Dataportaal_
gerealiseerd en het dataproduct meetdata wordt hierop aangeboden
|===
