name: Release new major version
on:
  workflow_dispatch:

defaults:
  run:
    shell: bash

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Tag version
        run: |
          git fetch && git fetch --tags
          LATEST_MAJOR=$(echo ${{ github.ref_name }} | cut -c 2- | cut -d . -f 1)
          NEW_MAJOR=$(echo $LATEST_MAJOR + 1 | bc)
          NEW_VERSION=$(echo v$NEW_MAJOR.0.0)

          git config user.name "CICD"
          git config user.email "cicd@netbeheernederland.nl"

          git checkout -b v$NEW_MAJOR
          git tag $NEW_VERSION
          git push -u origin v$NEW_MAJOR && git push --tags
          echo "NEW_VERSION=$NEW_VERSION" >> $GITHUB_ENV
      - name: Setup Python 3.12.7
        uses: actions/setup-python@v3
        with:
          python-version: "3.12.7"
      - name: Install Poetry 1.8.4
        run: curl -sSL https://install.python-poetry.org | python3 - --version 1.8.4
      - name: Install Python project dependencies
        run: $HOME/.local/bin/poetry install --no-root
      - name: Install Just 1.38.0
        run: pip install rust-just==1.38.0
      - name: Generate documentation and schemas
        run: |
          just gen-all
      - name: Commit artifacts to `docs` branch
        run: |
          git config user.name "CICD"
          git config user.email "cicd@netbeheernederland.nl"
          git fetch
          git checkout docs

          if [ -d "${{ env.NEW_VERSION }}" ]; then
            exit 1
          fi

          mv artifacts/documentation "${{ github.ref_name }}"

          git add "${{ env.NEW_VERSION }}"
          git commit -m "Added docs and schemas for ${{ env.NEW_VERSION }}"
          git push
      - name: Prepare release
        run: echo "New version." > release_notes.txt
      - name: Release
        uses: softprops/action-gh-release@v2
        with:
          body_path: release_notes.txt
          tag_name: ${{ env.NEW_VERSION }}
          files: |
            ${{ env.NEW_VERSION }}/modules/information-model/attachments/*.schema.linkml.yaml
            ${{ env.NEW_VERSION }}/modules/information-model/attachments/*.json_schema.json
